build: fix make build target
Before this PR, running `make` or `make build` would cause the following
error:
```
go build -o bin/hostbridge cmd/hostbridge/main.go
cmd/hostbridge/main.go:52:12: undefined: annotateCurrentNode
```

This commit fixes this.

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>