ds: remove `--nogpgcheck` dnf parameter
To allow Dockerfile.openshift to be built on Prow
CI, where the dnf ART wrapper is used:

```
[3/3] STEP 4/24: RUN groupadd --system --gid 92 frr &&     useradd --system --uid 92 --gid frr --home-dir /var/run/frr --shell /sbin/nologin --comment "FRRouting suite" frr &&     groupadd --system --gid 102 frrvty &&     usermod --append --groups frrvty frr
[3/3] STEP 5/24: RUN dnf --nogpgcheck install --setopt=install_weak_deps=0 --nodocs -y     frr grout iproute shadow-utils &&     chown -R frr:frr /etc/frr /var/run/frr
ART yum/dnf wrapper [7]: Checking for CI build pod repo definitions...
ART yum/dnf wrapper [7]: Installed CI build pod repo definitions from base-5-1-rhel10.ocp.svc.
ART yum/dnf wrapper [7]: DNF will search for repo files in: /etc/yum.repos.art/ci
ART yum/dnf wrapper [7]: Configured repositories in ci-svc-repos.repo:
ART yum/dnf wrapper [7]:   - rhel-10-baseos
ART yum/dnf wrapper [7]:   - rhel-10-appstream
ART yum/dnf wrapper [7]:   - rhel-10-fast-datapath
ART yum/dnf wrapper [7]:   - rhel-10-nfv
ART yum/dnf wrapper [7]:   - rhel-10-highavailability
ART yum/dnf wrapper [7]:   - rhel-10-server-ose-5.1
ART yum/dnf wrapper [7]:   - rhel-10-early-kernel
error: Unknown option --nogpgcheck
```

Signed-off-by: Andrea Panattoni <apanatto@redhat.com>