api, underlay: allow vlan sub-interfaces
This commit allows vlan sub-interfaces to be selected as underlay NICs.

Prior to this commit, attempting to use a vlan as underlay NIC would
fail with the following error:
```
error: underlays.openpe.openperouter.github.io "underlay" could not be patched: admission webhook "underlayvalidationwebhook.openperouter.io" denied the request: validation failed: invalid nic name for underlay underlay: eth0.123 - interface name eth0.123 contains invalid characters
```

The API validation was also fixed, which caused changes to the CRDs
composing the installation manifest.

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>